services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-broker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "8080:15672" # RabbitMQ Management UI
      - "5672:5672"  # RabbitMQ Broker port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJ_DIR=RabbitMq Producer
        - PROJ_FILE=ProducerEX1rabbitMQ.csproj
    container_name: producer-service
    ports:
      - "5000:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJ_DIR=RabbitMQ Consumer
        - PROJ_FILE=ConsumerEx1RabbitMQ.csproj
    container_name: consumer-service
    ports:
      - "5001:8080" 
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      rabbitmq:
        condition: service_healthy